# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 心跳测试

on:
  schedule:
    # 设置启动时间，为 UTC 时间, UTC23点 对应北京时间早7点
    - cron : '15 * * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run heart break
      run: |
        python heart_break.py
      env:
        TARGET_URL: ${{ secrets.TARGET_URL }}
        ORIGIN_URL: ${{ secrets.ORIGIN_URL }}
        REFERER_URL: ${{ secrets.REFERER_URL }}
